[2021-03-17 19:21:46,803] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: taxi.ExampleValidator 2021-03-17T23:20:17.726431+00:00 [queued]>
[2021-03-17 19:21:46,813] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: taxi.ExampleValidator 2021-03-17T23:20:17.726431+00:00 [queued]>
[2021-03-17 19:21:46,813] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-17 19:21:46,813] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-17 19:21:46,813] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-17 19:21:46,823] {taskinstance.py:1063} INFO - Executing <Task(AirflowComponent): ExampleValidator> on 2021-03-17T23:20:17.726431+00:00
[2021-03-17 19:21:46,828] {standard_task_runner.py:52} INFO - Started process 28889 to run task
[2021-03-17 19:21:46,837] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'taxi', 'ExampleValidator', '2021-03-17T23:20:17.726431+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/taxi_pipeline.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpavgmq3ms', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpnr3cmih2']
[2021-03-17 19:21:46,840] {standard_task_runner.py:77} INFO - Job 13: Subtask ExampleValidator
[2021-03-17 19:21:46,890] {logging_mixin.py:104} INFO - Running <TaskInstance: taxi.ExampleValidator 2021-03-17T23:20:17.726431+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-17 19:21:46,924] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=taxi
AIRFLOW_CTX_TASK_ID=ExampleValidator
AIRFLOW_CTX_EXECUTION_DATE=2021-03-17T23:20:17.726431+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-17T23:20:17.726431+00:00
[2021-03-17 19:21:46,932] {base_component_launcher.py:196} INFO - Running driver for ExampleValidator
[2021-03-17 19:21:46,941] {metadata_store.py:93} INFO - MetadataStore with DB connection initialized
[2021-03-17 19:21:46,969] {base_component_launcher.py:212} INFO - Running publisher for ExampleValidator
[2021-03-17 19:21:46,971] {metadata_store.py:93} INFO - MetadataStore with DB connection initialized
[2021-03-17 19:21:46,973] {python.py:118} INFO - Done. Returned value was: None
[2021-03-17 19:21:46,979] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=taxi, task_id=ExampleValidator, execution_date=20210317T232017, start_date=20210317T232146, end_date=20210317T232146
[2021-03-17 19:21:47,006] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-17 19:21:47,018] {local_task_job.py:146} INFO - Task exited with return code 0
