[2021-03-17 19:21:06,554] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: taxi.SchemaGen 2021-03-17T23:20:17.726431+00:00 [queued]>
[2021-03-17 19:21:06,562] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: taxi.SchemaGen 2021-03-17T23:20:17.726431+00:00 [queued]>
[2021-03-17 19:21:06,562] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-17 19:21:06,562] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-17 19:21:06,562] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-17 19:21:06,570] {taskinstance.py:1063} INFO - Executing <Task(AirflowComponent): SchemaGen> on 2021-03-17T23:20:17.726431+00:00
[2021-03-17 19:21:06,574] {standard_task_runner.py:52} INFO - Started process 28871 to run task
[2021-03-17 19:21:06,584] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'taxi', 'SchemaGen', '2021-03-17T23:20:17.726431+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/taxi_pipeline.py', '--cfg-path', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmpaexibpwx', '--error-file', '/var/folders/j6/755w2l7n4x1c9313788klj880000gq/T/tmptp6cfkw0']
[2021-03-17 19:21:06,591] {standard_task_runner.py:77} INFO - Job 11: Subtask SchemaGen
[2021-03-17 19:21:06,633] {logging_mixin.py:104} INFO - Running <TaskInstance: taxi.SchemaGen 2021-03-17T23:20:17.726431+00:00 [running]> on host 152.1.168.192.in-addr.arpa
[2021-03-17 19:21:06,669] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=taxi
AIRFLOW_CTX_TASK_ID=SchemaGen
AIRFLOW_CTX_EXECUTION_DATE=2021-03-17T23:20:17.726431+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-17T23:20:17.726431+00:00
[2021-03-17 19:21:06,675] {base_component_launcher.py:196} INFO - Running driver for SchemaGen
[2021-03-17 19:21:06,682] {metadata_store.py:93} INFO - MetadataStore with DB connection initialized
[2021-03-17 19:21:06,704] {base_component_launcher.py:212} INFO - Running publisher for SchemaGen
[2021-03-17 19:21:06,707] {metadata_store.py:93} INFO - MetadataStore with DB connection initialized
[2021-03-17 19:21:06,709] {python.py:118} INFO - Done. Returned value was: None
[2021-03-17 19:21:06,720] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=taxi, task_id=SchemaGen, execution_date=20210317T232017, start_date=20210317T232106, end_date=20210317T232106
[2021-03-17 19:21:06,757] {taskinstance.py:1220} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-03-17 19:21:06,767] {local_task_job.py:146} INFO - Task exited with return code 0
